# Generated by Django 3.0.1 on 2019-12-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the brand, this is unique', max_length=250, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='This is when it was created ')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='This is when we modified')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product and the name should be unique', max_length=250, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='This is when it was created ')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='This is when we modified')),
                ('parent_category', models.ForeignKey(help_text='This can be null', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The product name and is unique', max_length=250, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='This is when it was created ')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='This is when we modified')),
                ('brand', models.ForeignKey(help_text='The Brand the product belongs to', on_delete=django.db.models.deletion.CASCADE, to='product.Brand')),
                ('category', models.ForeignKey(help_text='The category the product belongs to', on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The Key for the specification, e.g:', max_length=250)),
                ('value', models.CharField(help_text='The value for the specification, e.g:', max_length=250)),
                ('unit', models.CharField(blank=True, help_text='The unit for the specification, eg:', max_length=250, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='This is when it was created ')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='This is when we modified')),
                ('product', models.ForeignKey(help_text='The specification for the particular product', on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
