# Generated by Django 3.0.1 on 2019-12-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='This can be null', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
