# Generated by Django 3.0.1 on 2019-12-23 11:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191223_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
